"""Host-compiled C parser cross-check (protocol-change skill, Task 2 step 6).

Compiles the REAL firmware parser (`firmware/scanner-stream/Src/rs_protocol.c`) with the
system C compiler -- not a reimplementation, not the ARM cross-compiler -- and drives it
through ctypes with vectors generated by `roomscan.protocol`. This is the check that a
change to one side (Python codec vs. C parser) cannot silently drift from the other: both
implementations must agree on every decoded field, not just "parses without crashing".

`rs_protocol.c`/`.h` are deliberately HAL-free (see their header comment) specifically so
this is possible without pulling in the STM32 HAL or any vendor headers.

No pre-existing C-compile cross-check harness was found elsewhere in this suite (searched
for `subprocess`/`ctypes.CDLL`/`rs_protocol` across tests/); this is the first one.
"""
from __future__ import annotations

import ctypes
import shutil
import struct
import subprocess
import zlib
from pathlib import Path

import pytest

from roomscan.protocol import (
    HEADER_SIZE, CommandCode, ManualParams, PowerMode, ProfileId, RangingMode,
    pack_command, pack_manual_command,
)

RS_PROTOCOL_DIR = Path(__file__).resolve().parents[2] / "firmware" / "scanner-stream" / "Src"
RS_PROTOCOL_C = RS_PROTOCOL_DIR / "rs_protocol.c"
RS_PROTOCOL_H = RS_PROTOCOL_DIR / "rs_protocol.h"

RS_PARSED_CMD_LEGACY = 0
RS_PARSED_CMD_MANUAL = 1

# Flat C shim: rs_parse_command's real return struct is a union, which is fragile to mirror
# byte-for-byte through ctypes across compilers/alignments. Instead the shim copies every
# field out through independent scalar out-pointers -- easy to bind correctly in ctypes,
# and it still calls the real rs_parse_command(), so the parsing logic under test is
# unmodified firmware source, not a reimplementation.
SHIM_SOURCE = """
#include <stdint.h>
#include <stddef.h>
#include "rs_protocol.h"

int32_t rs_parse_command_flat(const uint8_t *buf, size_t len,
                               uint8_t *out_version, uint32_t *out_token,
                               uint32_t *out_cmd, uint32_t *out_payload_len,
                               uint32_t *out_kind,
                               uint32_t *out_legacy_param,
                               uint8_t *out_manual_ranging_mode,
                               uint32_t *out_manual_frame_period_us,
                               uint16_t *out_manual_exposure_ms,
                               uint8_t *out_manual_power_mode) {
    rs_parsed_command_t pc;
    int32_t r = rs_parse_command(buf, len, &pc);
    if (r > 0) {
        *out_version = pc.version;
        *out_token = pc.token;
        *out_cmd = pc.cmd;
        *out_payload_len = pc.payload_len;
        *out_kind = (uint32_t)pc.kind;
        if (pc.kind == RS_PARSED_CMD_MANUAL) {
            *out_manual_ranging_mode = pc.u.manual.ranging_mode;
            *out_manual_frame_period_us = pc.u.manual.frame_period_us;
            *out_manual_exposure_ms = pc.u.manual.exposure_ms;
            *out_manual_power_mode = pc.u.manual.power_mode;
            *out_legacy_param = 0;
        } else {
            *out_legacy_param = pc.u.legacy.param;
            *out_manual_ranging_mode = 0;
            *out_manual_frame_period_us = 0;
            *out_manual_exposure_ms = 0;
            *out_manual_power_mode = 0;
        }
    }
    return r;
}
"""


def _cc() -> str | None:
    for candidate in ("cc", "gcc", "clang"):
        found = shutil.which(candidate)
        if found:
            return found
    return None


@pytest.fixture(scope="module")
def rs_parser_lib(tmp_path_factory):
    if not RS_PROTOCOL_C.exists() or not RS_PROTOCOL_H.exists():
        pytest.skip(f"firmware source not found at {RS_PROTOCOL_DIR}")
    cc = _cc()
    if cc is None:
        pytest.skip("no host C compiler (cc/gcc/clang) found on PATH")

    workdir = tmp_path_factory.mktemp("rs_protocol_crosscheck")
    shim_path = workdir / "rs_protocol_shim.c"
    shim_path.write_text(SHIM_SOURCE)
    so_path = workdir / "librs_protocol_crosscheck.so"

    cmd = [
        cc, "-std=c11", "-Wall", "-Wextra", "-fPIC", "-shared", "-O0",
        "-I", str(RS_PROTOCOL_DIR),
        "-o", str(so_path),
        str(shim_path), str(RS_PROTOCOL_C),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        pytest.fail(
            f"host compile of rs_protocol.c failed (cmd={cmd!r}):\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}")

    lib = ctypes.CDLL(str(so_path))
    lib.rs_parse_command_flat.argtypes = [
        ctypes.c_char_p, ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint32),
        ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32),
        ctypes.POINTER(ctypes.c_uint32),
        ctypes.POINTER(ctypes.c_uint32),
        ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint32),
        ctypes.POINTER(ctypes.c_uint16), ctypes.POINTER(ctypes.c_uint8),
    ]
    lib.rs_parse_command_flat.restype = ctypes.c_int32
    return lib


class CParseResult:
    """Python-side mirror of one rs_parse_command_flat() call."""

    def __init__(self):
        self.version = ctypes.c_uint8(0)
        self.token = ctypes.c_uint32(0)
        self.cmd = ctypes.c_uint32(0)
        self.payload_len = ctypes.c_uint32(0)
        self.kind = ctypes.c_uint32(0)
        self.legacy_param = ctypes.c_uint32(0)
        self.manual_ranging_mode = ctypes.c_uint8(0)
        self.manual_frame_period_us = ctypes.c_uint32(0)
        self.manual_exposure_ms = ctypes.c_uint16(0)
        self.manual_power_mode = ctypes.c_uint8(0)


def _c_parse(lib, buf: bytes) -> tuple[int, CParseResult]:
    r = CParseResult()
    ret = lib.rs_parse_command_flat(
        buf, len(buf),
        ctypes.byref(r.version), ctypes.byref(r.token),
        ctypes.byref(r.cmd), ctypes.byref(r.payload_len),
        ctypes.byref(r.kind),
        ctypes.byref(r.legacy_param),
        ctypes.byref(r.manual_ranging_mode), ctypes.byref(r.manual_frame_period_us),
        ctypes.byref(r.manual_exposure_ms), ctypes.byref(r.manual_power_mode),
    )
    return ret, r


# --- Python-generated v2 vectors fed to the real C parser --------------------------------

@pytest.mark.parametrize("cmd,param,token", [
    (CommandCode.PING, 0, 1),
    (CommandCode.SET_STANDBY, 2, 0xFFFF_FFFE),
    (CommandCode.SET_RANGING_PROFILE, ProfileId.HIGH_FRAMERATE, 12345),
    (CommandCode.GET_RANGING_CONFIG, 0, 7),
    (CommandCode.SET_IMU_ENV_RATE, 90, 8),
    (CommandCode.GET_IMU_ENV_RATE, 0, 9),
])
def test_c_parser_decodes_legacy_command_matching_python(rs_parser_lib, cmd, param, token):
    frame = pack_command(cmd, param, token)
    ret, r = _c_parse(rs_parser_lib, frame)
    assert ret == len(frame)
    assert r.version.value == 2
    assert r.token.value == token
    assert r.cmd.value == cmd
    assert r.payload_len.value == 8
    assert r.kind.value == RS_PARSED_CMD_LEGACY
    assert r.legacy_param.value == param


def test_c_parser_decodes_manual_command_matching_python(rs_parser_lib):
    params = ManualParams(ranging_mode=RangingMode.PRECISION, frame_period_us=11_111,
                          exposure_ms=4, power_mode=PowerMode.REGULAR)
    frame = pack_manual_command(params, token=55)
    ret, r = _c_parse(rs_parser_lib, frame)
    assert ret == len(frame) == HEADER_SIZE + 12 + 4
    assert r.version.value == 2
    assert r.token.value == 55
    assert r.cmd.value == CommandCode.SET_MANUAL_PARAMS
    assert r.payload_len.value == 12
    assert r.kind.value == RS_PARSED_CMD_MANUAL
    assert r.manual_ranging_mode.value == RangingMode.PRECISION
    assert r.manual_frame_period_us.value == 11_111
    assert r.manual_exposure_ms.value == 4
    assert r.manual_power_mode.value == PowerMode.REGULAR


def test_c_parser_manual_command_boundary_values(rs_parser_lib):
    """u8/u32/u16/u8 field boundaries -- catches any off-by-one in the manual shape's
    hand-computed byte offsets (RS_HEADER_SIZE + 4/5/9/11 in rs_protocol.c)."""
    params = ManualParams(ranging_mode=255, frame_period_us=0xFFFFFFFF,
                          exposure_ms=0xFFFF, power_mode=255)
    frame = pack_manual_command(params, token=1)
    ret, r = _c_parse(rs_parser_lib, frame)
    assert ret > 0
    assert r.manual_ranging_mode.value == 255
    assert r.manual_frame_period_us.value == 0xFFFFFFFF
    assert r.manual_exposure_ms.value == 0xFFFF
    assert r.manual_power_mode.value == 255


# --- concatenated commands and split magic ------------------------------------------------

def test_c_parser_concatenated_44_and_48_byte_commands(rs_parser_lib):
    """A legacy (44-byte wire) command immediately followed by a manual (48-byte wire)
    command in one buffer -- the length must come from each frame's own header, not one
    global constant."""
    legacy = pack_command(CommandCode.SET_RANGING_PROFILE, ProfileId.PRECISION, token=1)
    manual = pack_manual_command(
        ManualParams(RangingMode.AMBIENT, 33_333, 6, PowerMode.ULP), token=2)
    buf = legacy + manual

    ret1, r1 = _c_parse(rs_parser_lib, buf)
    assert ret1 == len(legacy)
    assert r1.kind.value == RS_PARSED_CMD_LEGACY
    assert r1.token.value == 1

    ret2, r2 = _c_parse(rs_parser_lib, buf[ret1:])
    assert ret2 == len(manual)
    assert r2.kind.value == RS_PARSED_CMD_MANUAL
    assert r2.token.value == 2
    assert r2.manual_frame_period_us.value == 33_333


def test_c_parser_magic_split_across_reads(rs_parser_lib):
    """The magic bytes themselves straddle two reads -- the parser must not consume or
    reject anything until the full magic (and then the full header) is available."""
    frame = pack_manual_command(
        ManualParams(RangingMode.PRECISION, 11_111, 4, PowerMode.REGULAR), token=9)

    # Only 2 of the 4 magic bytes present: nothing to find yet, must wait (not error).
    ret, _ = _c_parse(rs_parser_lib, frame[:2])
    assert ret <= 0  # "keep waiting", never a positive (successful) parse

    # Only the header partially present (magic complete, but < 32 bytes total): pending.
    ret, _ = _c_parse(rs_parser_lib, frame[:20])
    assert ret <= 0

    # Header complete (32 bytes) but body/CRC not yet: still pending, not rejected.
    ret, _ = _c_parse(rs_parser_lib, frame[:HEADER_SIZE])
    assert ret <= 0

    # Full frame: now it parses.
    ret, r = _c_parse(rs_parser_lib, frame)
    assert ret == len(frame)
    assert r.kind.value == RS_PARSED_CMD_MANUAL


def test_c_parser_garbage_prefix_resyncs(rs_parser_lib):
    """Per rs_parse_command's documented contract: when a full, valid frame follows a
    garbage prefix in the SAME buffer, one call both skips the garbage and decodes the
    frame -- the positive return is `k + frame_total` (garbage prefix plus the consumed
    frame), not just the frame's own length. The caller's job is to consume that many
    bytes from the front; it does not need (or get) a separate resync step first."""
    noise = b"boot log noise before the first command\r\n"
    frame = pack_command(CommandCode.PING, 0, token=3)
    buf = noise + frame

    ret, r = _c_parse(rs_parser_lib, buf)
    assert ret == len(noise) + len(frame)
    assert r.cmd.value == CommandCode.PING
    assert r.token.value == 3

    # A garbage prefix with NO valid frame after it (buffer ends mid-noise, no magic at
    # all) is the pure resync case: negative, "drop everything (minus a 3-byte tail)".
    ret2, _ = _c_parse(rs_parser_lib, noise)
    assert ret2 < 0
    assert -ret2 >= len(noise) - 3


# --- invalid enum / reserved values ---------------------------------------------------------

def test_c_parser_rejects_reserved_payload_len(rs_parser_lib):
    """A payload_len that is neither RS_CMD_PAYLOAD_LEN (8) nor RS_CMD_MANUAL_PAYLOAD_LEN
    (12) is not a shape any COMMAND uses -- the parser must resync, not misread bytes as
    one of the two known shapes."""
    header = struct.pack("<4sBBBBIQHHII", b"RSCN", 2, 3, 0, 0, 1, 0, 0, 0, 10, 0)
    payload = b"\x00" * 10
    frame = header + payload + zlib.crc32(header + payload).to_bytes(4, "little")
    ret, _ = _c_parse(rs_parser_lib, frame)
    assert ret < 0  # resync, never a positive parse of garbage as a known shape


def test_c_parser_rejects_wrong_version(rs_parser_lib):
    frame = bytearray(pack_command(CommandCode.PING, 0, token=1))
    frame[4] = 1  # v1 -- the firmware only accepts RS_PROTO_VERSION (2)
    ret, _ = _c_parse(rs_parser_lib, bytes(frame))
    assert ret < 0


def test_c_parser_rejects_wrong_frame_type(rs_parser_lib):
    frame = bytearray(pack_command(CommandCode.PING, 0, token=1))
    frame[5] = 4  # ACK, not COMMAND
    ret, _ = _c_parse(rs_parser_lib, bytes(frame))
    assert ret < 0


def test_c_parser_rejects_corrupt_crc(rs_parser_lib):
    frame = bytearray(pack_manual_command(
        ManualParams(RangingMode.PRECISION, 11_111, 4, PowerMode.REGULAR), token=1))
    frame[HEADER_SIZE] ^= 0xFF  # flip a payload byte, invalidating the CRC
    ret, _ = _c_parse(rs_parser_lib, bytes(frame))
    assert ret < 0


# --- oversize rejection -----------------------------------------------------------------

def test_c_parser_does_not_overread_on_truncated_manual_frame(rs_parser_lib):
    """A manual-shaped header (payload_len == 12) whose buffer is shorter than the full
    48-byte frame must be treated as pending, never read past the end of the buffer
    (this is exactly what ASan/valgrind would catch; the assertion here is behavioral --
    zero or negative return -- since ctypes itself won't detect an OOB read reliably)."""
    frame = pack_manual_command(
        ManualParams(RangingMode.PRECISION, 11_111, 4, PowerMode.REGULAR), token=1)
    for cutoff in range(HEADER_SIZE, len(frame)):
        ret, _ = _c_parse(rs_parser_lib, frame[:cutoff])
        assert ret <= 0, f"cutoff={cutoff} must not report a successful parse"


# --- EVENT code 7 (TX_QUEUE_STATS) encoder cross-check --------------------------------------
#
# Every cross-check above exercises the DECODE direction: a Python-built COMMAND vector fed
# to the real C rs_parse_command(). TX_QUEUE_STATS runs the other way -- firmware ENCODES
# it (rs_send_tx_queue_stats_event() + rs_send_generic_cdc() in
# firmware/scanner-stream/Src/vl53l9_app.c), the host only ever DECODES it
# (roomscan.protocol.parse_tx_queue_stats_event) -- so there is no Python-side encoder to
# feed the C parser. What CAN be cross-checked without pulling in vl53l9_app.c's TinyUSB/
# lwIP dependencies (it is not HAL-free) is the byte-level construction: rs_write_header(),
# rs_crc32(), and rs_put_u32() are the exact three primitives rs_send_generic_cdc() and
# rs_send_tx_queue_stats_event() call to build the frame, they are non-static and declared
# in rs_protocol.h, and they are already linked into rs_parser_lib's .so -- so this test
# calls the REAL compiled functions (not a reimplementation) to build the same frame the
# firmware would, and checks it byte-for-byte against golden_tx_queue_stats.bin (which
# make_fixtures.py built independently via raw struct/zlib) and against what
# parse_tx_queue_stats_event() decodes. The one thing this does NOT reach is the bit-
# packing formula inline in rs_send_tx_queue_stats_event() itself (that line lives in
# vl53l9_app.c, not rs_protocol.c) -- that formula is instead verified by direct reading
# (docs/protocol.md's EVENT table, the firmware source, and protocol.py's decode formula
# all agree: detail = high_water | (transport << 8) | (pending << 16)).

@pytest.fixture(scope="module")
def rs_protocol_primitives(rs_parser_lib):
    """Bind the real rs_write_header/rs_crc32/rs_put_u32 symbols (already compiled into
    rs_parser_lib's .so, since they are non-static functions in rs_protocol.c) for direct
    ctypes calls -- no shim needed, these are the firmware's actual encoder primitives."""
    lib = rs_parser_lib
    lib.rs_put_u32.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_uint32]
    lib.rs_put_u32.restype = None
    lib.rs_write_header.argtypes = [
        ctypes.POINTER(ctypes.c_uint8), ctypes.c_uint8, ctypes.c_uint8, ctypes.c_uint8,
        ctypes.c_uint32, ctypes.c_uint64, ctypes.c_uint16, ctypes.c_uint16, ctypes.c_uint32,
    ]
    lib.rs_write_header.restype = None
    lib.rs_crc32.argtypes = [ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t]
    lib.rs_crc32.restype = ctypes.c_uint32
    return lib


def _u8p(buf: "ctypes.Array[ctypes.c_uint8]", offset: int = 0) -> ctypes.POINTER:
    return ctypes.cast(ctypes.addressof(buf) + offset, ctypes.POINTER(ctypes.c_uint8))


def test_c_encoder_builds_tx_queue_stats_frame_matching_golden(rs_protocol_primitives):
    lib = rs_protocol_primitives

    # Same values as make_fixtures.golden_tx_queue_stats() / docs/protocol.md's worked
    # example, packed the same way rs_send_tx_queue_stats_event() packs `detail`.
    high_water, active_transport, pending = 200, 2, 1000
    enqueue_drops, stack_stalls, emitted_bytes = 7, 3, 123_456_789
    detail = (high_water & 0xFF) | ((active_transport & 0xFF) << 8) | ((pending & 0xFFFF) << 16)
    assert detail == 0x03E802C8

    # Payload: 5 x rs_put_u32 at offsets 0/4/8/12/16, exactly as
    # rs_send_tx_queue_stats_event() writes it.
    payload_buf = (ctypes.c_uint8 * 20)()
    lib.rs_put_u32(_u8p(payload_buf, 0), 7)  # RS_EVT_TX_QUEUE_STATS
    lib.rs_put_u32(_u8p(payload_buf, 4), detail)
    lib.rs_put_u32(_u8p(payload_buf, 8), enqueue_drops)
    lib.rs_put_u32(_u8p(payload_buf, 12), stack_stalls)
    lib.rs_put_u32(_u8p(payload_buf, 16), emitted_bytes)
    payload_bytes = bytes(payload_buf)

    # Header + CRC: exactly rs_send_generic_cdc()'s construction -- rs_write_header(),
    # then rs_crc32() chained over header then payload.
    hdr_buf = (ctypes.c_uint8 * HEADER_SIZE)()
    lib.rs_write_header(_u8p(hdr_buf), 2, 0, 0, 4096, 987_654_321, 0, 0, 20)  # frame_type=EVENT(2)
    header_bytes = bytes(hdr_buf)

    crc = lib.rs_crc32(0, _u8p(hdr_buf), HEADER_SIZE)
    crc = lib.rs_crc32(crc, _u8p(payload_buf), 20)
    tail_buf = (ctypes.c_uint8 * 4)()
    lib.rs_put_u32(_u8p(tail_buf), crc)
    tail_bytes = bytes(tail_buf)

    c_frame = header_bytes + payload_bytes + tail_bytes

    golden = (Path(__file__).parent / "fixtures" / "golden_tx_queue_stats.bin").read_bytes()
    assert c_frame == golden, "C-built frame (real rs_write_header/rs_crc32/rs_put_u32) must match the golden fixture byte-for-byte"

    from roomscan.protocol import parse_tx_queue_stats_event
    ev = parse_tx_queue_stats_event(payload_bytes)
    assert ev.queue_high_water == 200
    assert ev.active_transport == "udp"
    assert ev.pending_fragments == 1000
    assert ev.enqueue_drops == 7
    assert ev.stack_stalls == 3
    assert ev.emitted_bytes == 123_456_789


def test_c_encoder_tx_queue_stats_detail_packing_disagreement_would_be_caught(rs_protocol_primitives):
    """Fail-proof for the encoder cross-check itself: corrupt one field going into the C
    build (as if the C packing formula had drifted from Python's) and confirm the byte
    comparison against the golden fixture goes red, not green."""
    lib = rs_protocol_primitives
    detail = (200 & 0xFF) | ((2 & 0xFF) << 8) | ((999 & 0xFFFF) << 16)  # pending off by one
    payload_buf = (ctypes.c_uint8 * 20)()
    lib.rs_put_u32(_u8p(payload_buf, 0), 7)
    lib.rs_put_u32(_u8p(payload_buf, 4), detail)
    lib.rs_put_u32(_u8p(payload_buf, 8), 7)
    lib.rs_put_u32(_u8p(payload_buf, 12), 3)
    lib.rs_put_u32(_u8p(payload_buf, 16), 123_456_789)
    payload_bytes = bytes(payload_buf)

    golden = (Path(__file__).parent / "fixtures" / "golden_tx_queue_stats.bin").read_bytes()
    golden_payload = golden[HEADER_SIZE:HEADER_SIZE + 20]
    assert payload_bytes != golden_payload  # proves the comparison above is discriminating


def test_python_is_independent_of_c_source_availability(monkeypatch):
    """Sanity: the Python-side codec functions used above import and work even without a
    C compiler present (skip-guarded above) -- this test has no rs_parser_lib dependency
    on purpose, so `pytest -k crosscheck` run on a box without a C toolchain still proves
    the vectors it WOULD have fed the C parser are well-formed."""
    params = ManualParams(RangingMode.AMBIENT, 33_333, 6, PowerMode.ULP)
    frame = pack_manual_command(params, token=1)
    assert len(frame) == HEADER_SIZE + 12 + 4
